/* HMG Enterprise v4.0 — Shared Utilities */
function toggleMenu(){const m=document.getElementById('mobileMenu');if(m)m.style.display=m.style.display==='flex'?'none':'flex'}
let toastTimer=null;function showToast(msg){const t=document.getElementById('toast'),m=document.getElementById('toastMsg');if(!t||!m)return;m.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
document.addEventListener('keydown',function(e){if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA'||e.target.tagName==='SELECT')return;if(e.altKey){const map={d:'index.html',s:'sales.html',i:'inventory.html',r:'reports.html',e:'expenses.html',c:'customers.html',u:'suppliers.html',g:'register.html',n:'journal.html',o:'staff.html',b:'budgets.html',t:'credits.html'};const dest=map[e.key.toLowerCase()];if(dest){e.preventDefault();window.location.href=dest}}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
function applyTheme(){let t=localStorage.getItem('st_theme');if(t)try{t=JSON.parse(t)}catch(e){t=null}if(!t)return;const r=document.documentElement,v={dark_green:{bg:'#0a0d12',surface:'#111620',surface2:'#181f2e',accent:'#00e5a0',accent2:'#0077ff',accent3:'#ff6b35',text:'#e8edf5',muted:'#6b7a94'},dark_blue:{bg:'#080f1a',surface:'#0d1829',surface2:'#152035',accent:'#38bdf8',accent2:'#818cf8',accent3:'#f472b6',text:'#e2e8f0',muted:'#64748b'},dark_purple:{bg:'#0c0816',surface:'#150f24',surface2:'#1e1635',accent:'#a78bfa',accent2:'#f472b6',accent3:'#38bdf8',text:'#e8e0f5',muted:'#8b7aa8'},dark_red:{bg:'#120a0a',surface:'#1c1010',surface2:'#2a1818',accent:'#f87171',accent2:'#fbbf24',accent3:'#60a5fa',text:'#f5e8e8',muted:'#946b6b'},light:{bg:'#f3f4f6',surface:'#ffffff',surface2:'#f9fafb',accent:'#059669',accent2:'#2563eb',accent3:'#ea580c',text:'#1f2937',muted:'#6b7280'}};const c=v[t];if(!c)return;Object.entries({'--bg':c.bg,'--surface':c.surface,'--surface2':c.surface2,'--accent':c.accent,'--accent2':c.accent2,'--accent3':c.accent3,'--text':c.text,'--muted':c.muted}).forEach(([k,val])=>r.style.setProperty(k,val));if(t==='light'){r.style.setProperty('--border','rgba(0,0,0,0.08)');r.style.setProperty('--danger','#dc2626');r.style.setProperty('--warning','#d97706');r.style.setProperty('--success','#059669');document.body.classList.add('light-theme')}else{r.style.setProperty('--border','rgba(255,255,255,0.07)');r.style.setProperty('--danger','#ff4757');r.style.setProperty('--warning','#ffd32a');r.style.setProperty('--success',c.accent);document.body.classList.remove('light-theme')}}
applyTheme();
function shareWhatsApp(text){window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')}
function generateShareSummary(period){const cfg=ST.config(),sales=ST.sales(),exps=ST.expenses(),now=new Date();let f=sales,pe=0;
if(period==='today'){const ts=now.toDateString();f=sales.filter(s=>new Date(s.date).toDateString()===ts);pe=exps.filter(e=>new Date(e.date).toDateString()===ts).reduce((a,e)=>a+e.amount,0)}
else if(period==='week'){const wa=new Date(now-7*86400000);f=sales.filter(s=>new Date(s.date)>=wa);pe=exps.filter(e=>new Date(e.date)>=wa).reduce((a,e)=>a+e.amount,0)}
else if(period==='month'){f=sales.filter(s=>{const d=new Date(s.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});pe=exps.filter(e=>{const d=new Date(e.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((a,e)=>a+e.amount,0)}
else{pe=exps.reduce((a,e)=>a+e.amount,0)}
const rev=f.reduce((a,s)=>a+s.total,0),gp=f.reduce((a,s)=>a+(s.profit||0),0),pLabel=period==='today'?'Today':period==='week'?'This Week':period==='month'?'This Month':'All Time';
return `📊 *${cfg.businessName} — Sales Report*\n━━━━━━━━━━━━━━━━━━\n📅 ${pLabel}\n\n💰 Revenue: ${ST.fmt(rev)}\n📦 Transactions: ${f.length}\n💵 Gross Profit: ${ST.fmt(gp)}\n💸 Expenses: ${ST.fmt(pe)}\n📈 Net Profit: ${ST.fmt(gp-pe)}\n\n━━━━━━━━━━━━━━━━━━\n${cfg.brandTagline}\n🌐 ${cfg.brandWebsite}\nPowered by HMG Concepts`}

// PIN Guard
(function checkPin(){const pin=localStorage.getItem('st_pin');if(!pin)return;const sp=pin.replace(/^"|"$/g,'');if(!sp||sessionStorage.getItem('st_unlocked')==='1')return;
const o=document.createElement('div');o.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,0.95);z-index:9999;display:flex;align-items:center;justify-content:center;padding:1rem';
o.innerHTML=`<div style="text-align:center;max-width:300px;width:100%"><div style="font-family:Syne,sans-serif;font-size:1.2rem;font-weight:800;color:#00e5a0;margin-bottom:0.2rem">HMG Enterprise</div><div style="color:#6b7a94;font-size:0.8rem;margin-bottom:1.2rem">Enter your 4-digit PIN</div><input type="password" id="pinInput" maxlength="4" placeholder="• • • •" style="background:#181f2e;border:1px solid rgba(255,255,255,0.1);border-radius:8px;color:#e8edf5;padding:0.7rem;font-size:1.4rem;text-align:center;letter-spacing:0.5em;width:100%;font-family:monospace" /><button onclick="verifyPIN()" style="margin-top:0.8rem;width:100%;padding:0.65rem;border:none;border-radius:8px;background:linear-gradient(135deg,#00e5a0,#00c47a);color:#000;font-family:Syne,sans-serif;font-weight:700;font-size:0.95rem;cursor:pointer">Unlock</button><div id="pinError" style="color:#ff4757;font-size:0.78rem;margin-top:0.6rem"></div></div>`;
document.body.appendChild(o);
window.verifyPIN=function(){if(document.getElementById('pinInput').value===sp){sessionStorage.setItem('st_unlocked','1');o.remove()}else{document.getElementById('pinError').textContent='Incorrect PIN.';document.getElementById('pinInput').value='';document.getElementById('pinInput').focus()}};
document.getElementById('pinInput').addEventListener('keyup',function(e){if(e.key==='Enter')window.verifyPIN()});
setTimeout(()=>{const i=document.getElementById('pinInput');if(i)i.focus()},100)})();

document.addEventListener('DOMContentLoaded',function(){const e=document.getElementById('bizNameNav');if(e)try{e.textContent=ST.config().businessName||'HMG Concepts'}catch(x){}});
